export default {
  name: "默认浅色",
  key: "defaultLight",
  list: [
    {
      type: "color",
      label: "主色",
      desc: "",
      name: "--color-primary",
      value: "#3b82f6",
    },
    {
      type: "color",
      label: "主色",
      desc: "次要",
      name: "--color-primary-secondary",
      value: "#c7d7f1",
    },
    {
      type: "color",
      label: "主色",
      desc: "禁用状态",
      name: "--color-primary-disabled",
      value: "#133263",
    },
    {
      type: "color",
      label: "主色",
      desc: "浮动状态",
      name: "--color-primary-hover",
      value: "#5893f1",
    },
    {
      type: "color",
      label: "主色",
      desc: "激活状态",
      name: "--color-primary-active",
      value: "#2e74e6",
    },
    {
      type: "color",
      label: "状态色",
      desc: "默认",
      name: "--color-status-default",
      value: "#9e9e9e",
    },
    {
      type: "color",
      label: "状态色",
      desc: "默认次要",
      name: "--color-status-default-secondary",
      value: "#f5f5f5",
    },
    {
      type: "color",
      label: "状态色",
      desc: "进行中",
      name: "--color-status-processing",
      value: "#2196f3",
    },
    {
      type: "color",
      label: "状态色",
      desc: "进行中次要",
      name: "--color-status-processing-secondary",
      value: "#bbdefb",
    },
    {
      type: "color",
      label: "状态色",
      desc: "成功",
      name: "--color-status-success",
      value: "#4caf50",
    },
    {
      type: "color",
      label: "状态色",
      desc: "成功次要",
      name: "--color-status-success-secondary",
      value: "#e2f4e3",
      _changed: true,
    },
    {
      type: "color",
      label: "状态色",
      desc: "警告",
      name: "--color-status-warning",
      value: "#ff9800",
    },
    {
      type: "color",
      label: "状态色",
      desc: "警告次要",
      name: "--color-status-warning-secondary",
      value: "#ffecb3",
    },
    {
      type: "color",
      label: "状态色",
      desc: "错误",
      name: "--color-status-error",
      value: "#f44336",
    },
    {
      type: "color",
      label: "状态色",
      desc: "错误次要",
      name: "--color-status-error-secondary",
      value: "#ffcdd2",
    },
    {
      type: "color",
      label: "文字颜色",
      desc: "",
      name: "--color-text",
      value: "#393939",
    },
    {
      type: "color",
      label: "文字颜色",
      desc: "次要",
      name: "--color-text-secondary",
      value: "#535353",
    },
    {
      type: "color",
      label: "文字反色",
      desc: "",
      name: "--color-text-inverse",
      value: "#f8fafc",
    },
    {
      type: "color",
      label: "文字标题颜色",
      desc: "",
      name: "--color-text-heading",
      value: "#03255c",
    },
    {
      type: "color",
      label: "文字描述颜色",
      desc: "",
      name: "--color-text-desc",
      value: "#a9a9a9",
    },
    {
      type: "color",
      label: "文字颜色，禁用状态",
      desc: "",
      name: "--color-text-disabled",
      value: "#737373",
    },
    {
      type: "color",
      label: "文字颜色",
      desc: "浮动状态",
      name: "--color-text-hover",
      value: "#4d4d4d",
    },
    {
      type: "color",
      label: "文字颜色",
      desc: "激活状态",
      name: "--color-text-active",
      value: "#3b82f6",
    },
    {
      type: "color",
      label: "背景色",
      desc: "",
      name: "--color-bg",
      value: "#f5f5f5",
    },
    {
      type: "color",
      label: "背景次要颜色",
      desc: "",
      name: "--color-bg-secondary",
      value: "#f1f1f1",
    },
    {
      type: "color",
      label: "背景反色",
      desc: "",
      name: "--color-bg-inverse",
      value: "#1e293b",
    },
    {
      type: "color",
      label: "布局顶栏背景色",
      desc: "",
      name: "--color-bg-layout-header",
      value: "#ffffff",
    },
    {
      type: "color",
      label: "布局侧栏背景色",
      desc: "",
      name: "--color-bg-layout-side",
      value: "#ffffff",
    },
    {
      type: "color",
      label: "组件背景色",
      desc: "",
      name: "--color-bg-component",
      value: "#ffffff",
    },
    {
      type: "color",
      label: "组件背景色",
      desc: "次要",
      name: "--color-bg-component-secondary",
      value: "#f9f9f9",
    },
    {
      type: "color",
      label: "组件背景色",
      desc: "禁用状态",
      name: "--color-bg-component-disabled",
      value: "#e2e2e2",
    },
    {
      type: "color",
      label: "组件背景色",
      desc: "浮动状态",
      name: "--color-bg-component-hover",
      value: "#f1f1f1",
    },
    {
      type: "color",
      label: "组件背景颜色",
      desc: "激活状态",
      name: "--color-bg-component-active",
      value: "#3b82f6",
    },
    {
      type: "color",
      label: "弹出层背景色",
      desc: "",
      name: "--color-bg-popover",
      value: "#ffffff",
    },
    {
      type: "color",
      label: "背景色，占用",
      desc: "",
      name: "--color-bg-placeholder",
      value: "#9ca3af",
    },
    {
      type: "color",
      label: "背景色，遮罩",
      desc: "",
      name: "--color-bg-mask",
      value: "rgba(0,0,0,0.3)",
    },
    {
      type: "color",
      label: "背景色，模糊背景",
      desc: "",
      name: "--color-bg-blur",
      value: "rgba(55,65,81,0.1)",
    },
    {
      type: "color",
      label: "边框颜色",
      desc: "",
      name: "--color-border",
      value: "#d9d9d9",
    },
    {
      type: "color",
      label: "边框颜色，次要",
      desc: "",
      name: "--color-border-secondary",
      value: "#e5e5e5",
    },
    {
      type: "color",
      label: "边框颜色，反色",
      desc: "",
      name: "--color-border-inverse",
      value: "#414141",
    },
    {
      type: "color",
      label: "边框颜色",
      desc: "禁用状态",
      name: "--color-border-disabled",
      value: "#d1d1d1",
    },
    {
      type: "color",
      label: "边框颜色",
      desc: "悬浮状态",
      name: "--color-border-hover",
      value: "#e9e9e9",
    },
    {
      type: "color",
      label: "边框颜色",
      desc: "激活状态",
      name: "--color-border-active",
      value: "#3b82f6",
    },
    {
      type: "input",
      label: "背景图",
      desc: "登录页",
      name: "--image-bg-layout-login",
      value: "unset",
    },
    {
      type: "input",
      label: "背景图",
      desc: "布局顶栏",
      name: "--image-bg-layout-header",
      value: "unset",
    },
    {
      type: "input",
      label: "背景图",
      desc: "布局主体",
      name: "--image-bg-layout-body",
      value: "unset",
    },
    {
      type: "input",
      label: "背景图",
      desc: "布局侧栏",
      name: "--image-bg-layout-side",
      value: "unset",
    },
    {
      type: "pixel",
      label: "圆角尺寸",
      desc: "",
      name: "--size-border-radius",
      value: "6px",
    },
    {
      type: "pixel",
      label: "圆角小尺寸",
      desc: "",
      name: "--size-border-radius-sm",
      value: "4px",
    },
    {
      type: "pixel",
      label: "圆角大尺寸",
      desc: "",
      name: "--size-border-radius-lg",
      value: "8px",
    },
    {
      type: "pixel",
      label: "边框尺寸",
      desc: "",
      name: "--size-border-width",
      value: "1px",
    },
    {
      type: "pixel",
      label: "内容间隙",
      desc: "",
      name: "--size-cell-gap",
      value: "16px",
    },
    {
      type: "pixel",
      label: "内容间隙小尺寸",
      desc: "",
      name: "--size-cell-gap-sm",
      value: "8px",
    },
    {
      type: "pixel",
      label: "内容间隙大尺寸",
      desc: "",
      name: "--size-cell-gap-lg",
      value: "24px",
    },
    {
      type: "pixel",
      label: "默认页面顶栏高度",
      desc: "",
      name: "--size-layout-header-height",
      value: "52px",
    },
    {
      type: "pixel",
      label: "页面顶栏扩展高度",
      desc: "可以显示更多信息",
      name: "--size-layout-header-height-expand",
      value: "78px",
    },
    {
      type: "pixel",
      label: "内容固定宽度尺寸",
      desc: "",
      name: "--size-layout-content-width",
      value: "1400px",
    },
    {
      type: "input",
      label: "字体",
      desc: "",
      name: "font-family",
      value:
        '-apple-system,BlinkMacSystemFont,"SegoeUI",Roboto,"HelveticaNeue",Arial,"NotoSans",sans-serif,"AppleColorEmoji","SegoeUIEmoji","SegoeUISymbol","NotoColorEmoji"',
    },
    {
      type: "input",
      label: "系统色调",
      desc: "",
      name: "color-scheme",
      value: "light",
    },
    {
      type: "input",
      label: "系统强调色",
      desc: "",
      name: "accent-color",
      value: "var(--color-primary)",
    },
  ],
};
